image: node:lts

stages:
  - install
  - test
  - build
  - publish

cache:
  key: m3-cache
  paths:
    - dist/.cache/

dependencies:
  stage: install
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - yarn test
